version: '3'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - GARMIN_USERNAME=${GARMIN_USERNAME}
      - GARMIN_PASSWORD=${GARMIN_PASSWORD}
    depends_on:
      - db
    command: streamlit run app/main.py
    restart: unless-stopped

  db:
    image: sqlite:latest
    volumes:
      - ./data:/data
    restart: unless-stopped