version: '3'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./data:/app/data  # SQLiteファイルを保存するデータディレクトリをマウント
    environment:
      - GARMIN_USERNAME=${GARMIN_USERNAME}
      - GARMIN_PASSWORD=${GARMIN_PASSWORD}
    command: streamlit run app/main.py
    restart: unless-stopped